name: Generate Snake

# Controls when the action will run
on:
  schedule:
    # runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: platane/snk@v3
        with:
          github_user_name: devXvidit # MAKE SURE THIS MATCHES YOUR USERNAME
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#8BC34A,#689F38,#388E3C,#1B5E20
      - name: push svg content
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
